# Generated by Django 2.2.3 on 2019-07-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190727_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userName',
            field=models.TextField(blank=True),
        ),
    ]
